### Crear un Vehículo
POST http://localhost:5002/api/vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI1NjQ2NTU5LCJleHAiOjE3MjYyNTEzNTl9.yxgFLST1qbjaoZ7QAZ0t6KCKONNnuVeFle7FJP-8-08
Content-Type: application/json

{
  "brand": "Triumph",
  "model": "Tiger Sport 600",
  "nickname": "Mi Moto de carretera",
  "image": "https://media.triumphmotorcycles.co.uk/image/upload/f_auto/q_auto/sitecoremedialibrary/media-library/images/motorcycles/adventure-touring/my22/ll1%20tiger%20sport%20660/family/tiger-660-family-multi-small-v3-630x788.jpg"
}

###

# ### Obtener Todos los Vehículos del Usuario
# GET http://localhost:5002/api/vehicles/user
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI2ODM1NDgxLCJleHAiOjE3Mjc0NDAyODF9.1hT9ygufpe3m9CvihkZKs0gaJH5cAb9t3sfc7REle0U

### Obtener todos los vehiculos de un usuario
GET http://localhost:5002/api/vehicles/user/66d566bcc08191eee0ac1e4f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI3MDg3MjcwLCJleHAiOjE3Mjc2OTIwNzB9.HxXIjIoEt8W37YZ2G13tw2GkyunOd0tTkw2kDRYtW38

### Obtener un Vehículo por su ID
GET http://localhost:5002/api/vehicles/66d05cff1ddb3bff4c6f32ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDA1N2Q5MWZmNjI3MzkyZDI5NWU1ZCIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI0OTMxMDUyLCJleHAiOjE3MjU1MzU4NTJ9.vRWpg9VzLE-vPBwkNdgke9EWJf_Y-NxNRn6rVFznkJM

###

### Actualizar un Vehículo
PUT http://localhost:5002/api/vehicles/66d9e3c49309e6998c7efa07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI1NjQ2NTU5LCJleHAiOjE3MjYyNTEzNTl9.yxgFLST1qbjaoZ7QAZ0t6KCKONNnuVeFle7FJP-8-08
Content-Type: application/json

{
  "brand": "Yamaha",
  "model": "YZ450F",
  "nickname": "Actualizado",
  "image": "https://dirtbikemagazine.com/wp-content/uploads/2022/01/Eli-Tomac-Yamaha-YZ450F-3-scaled.jpg"
}

###

### Eliminar un Vehículo
DELETE http://localhost:5002/api/vehicles/66d05e1c364c6b8683d20d93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDA1N2Q5MWZmNjI3MzkyZDI5NWU1ZCIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI0OTMxMDUyLCJleHAiOjE3MjU1MzU4NTJ9.vRWpg9VzLE-vPBwkNdgke9EWJf_Y-NxNRn6rVFznkJM
