### Test de Login
POST http://localhost:5002/api/users/login
Content-Type: application/json

{
  "username": "cesaralvarezmarin@gmail.com",
  "password": "password"
}

### Test de Signup
POST http://localhost:5002/api/users/signup
Content-Type: application/json

{
  "username": "cesaralvarezmarin@gmail.com",
  "password": "password",
  "name": "César",
  "lastName": "Álvarez",
  "userAvatar": "https://avatars.githubusercontent.com/u/23705180?v=4&size=256",
  "description": "This is my bio description"
}

### Obtener todos los usuarios
GET http://localhost:5002/api/users
Content-Type: application/json

### Obtener info del usuario por ID
GET http://localhost:5002/api/users/66d566bcc08191eee0ac1e4f
Content-Type: application/json

### Obtener info del usuario autenticado
GET http://localhost:5002/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI1NjQ2NTU5LCJleHAiOjE3MjYyNTEzNTl9.yxgFLST1qbjaoZ7QAZ0t6KCKONNnuVeFle7FJP-8-08
Content-Type: application/json


### Actualizar el Perfil de Usuario
PUT http://localhost:5002/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI1NTUyMTI2LCJleHAiOjE3MjYxNTY5MjZ9.Q7lLBTFtXwlx5KR6uf7Vo-OlYU73nw1HQ3CeH6ztzcA
Content-Type: application/json

{
  "name": "César",
  "lastName": "Álvarez Marín",
  "userAvatar": "https://avatars.githubusercontent.com/u/23705180?v=4&size=256",
  "description": "Updated description",
  "enrolledEvents": [],
  "organizedEvents": [],
  "vehicles": []
}
