### Crear un nuevo evento
POST http://localhost:5002/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzljNTRiZGRlN2M3NzdlNjU1NDI5YyIsInVzZXJuYW1lIjoiY2VzYXIiLCJpYXQiOjE3MjQ1MDIwMzMsImV4cCI6MTcyNTEwNjgzM30.HJnXliDattPwB_e69rwlqMpEH4gd49_sDGqLSwvX3Kk

{
  "title": "Salida de Moto Carretera",
  "startDate": "2024-09-01T10:00:00Z",
  "endDate": "2024-09-01T14:00:00Z",
  "location": "C. Sta. Ana, 14, 41807 Espartinas, Sevilla, España",
  "locationCoordinates": {
    "type": "Point",
    "coordinates": [-6.128055, 37.380323]
  },
  "image": "https://i0.wp.com/pxsports.com/wp-content/uploads/2018/07/enduro.jpg?fit=1075%2C590",
  "description": "Una quedada para los amantes de las motos.",
  "eventType": "Quedadas"
}

### Obtener todos los eventos
GET http://localhost:5002/api/events
Content-Type: application/json

### Obtener info del evento por ID
GET http://localhost:5002/api/events/66ca46438033f805b454ae76
Content-Type: application/json

