### Test de Sign Up
POST http://localhost:5002/api/users
Content-Type: application/json

{
  "username": "cesar",
  "password": "password"
}

### Obtener todos los usuarios
GET http://localhost:5002/api/users
Content-Type: application/json

### Obtener info del usuario por ID
GET http://localhost:5002/api/users/66c9c54bdde7c777e655429c
Content-Type: application/json