### Crear un Evento
POST http://localhost:5002/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI1MjY5NTE4LCJleHAiOjE3MjU4NzQzMTh9.of-E9teLymsBRyUVxd5fo0G3VA8rPxxTBodW37vfxAU

{
  "title": "Enduro Race",
  "startDate": "2025-09-07T10:00:00Z",
  "endDate": "2025-09-07T14:00:00Z",
  "location": "Montes de Málaga, Spain",
  "shortLocation": "Málaga, Spain",
  "locationCoordinates": {
    "type": "Point",
    "coordinates": [-4.420340, 36.721302]
  },
  "image": "https://i0.wp.com/pxsports.com/wp-content/uploads/2018/07/enduro.jpg?fit=1075%2C590",
  "description": "Exciting enduro race in the mountains.",
  "eventType": "Adventure",
  "terrain": "offroad",
  "experience": "intermediate",
  "ticket": {
    "type": "free",
    "price": 0
  },
  "capacity": 20
}

### Obtener todos los eventos
GET http://localhost:5002/api/events
Content-Type: application/json

### Obtener Todos los Eventos (Filtrado)
GET http://localhost:5002/api/events?lat=36.721302&lng=-4.420340&radius=50&eventTypes=Competición&timeFilter=this_week
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDA1N2Q5MWZmNjI3MzkyZDI5NWU1ZCIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI0OTMxODM4LCJleHAiOjE3MjU1MzY2Mzh9.2yK4JtX5WTcx0R2MMXXk4XoPmtA23gBdpPW9zdOMEmE

### Obtener los eventos organizados y asistidos por un usuario
GET http://localhost:5002/api/events/66d566bcc08191eee0ac1e4f/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI3MDgyNDAwLCJleHAiOjE3Mjc2ODcyMDB9.njAfmUpBYOJ9bleBixg8Sh3ZFxzNiiMDjBVIYQxzCvY

### Test con un ID de usuario inválido
GET http://localhost:5002/api/events/invalidUserId/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI3MDgyNDAwLCJleHAiOjE3Mjc2ODcyMDB9.njAfmUpBYOJ9bleBixg8Sh3ZFxzNiiMDjBVIYQxzCvY

###

### Obtener un Evento por su ID
GET http://localhost:5002/api/events/66e1b60f981eddd7c2497897
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDk1MDAzYTI0Zjc2ZGVmN2QxY2ZiMiIsInVzZXJuYW1lIjoidGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3MjU1Njc1NTEsImV4cCI6MTcyNjE3MjM1MX0.lAtLzf2lpLv5H3diSG-gV3vJZ2CkiSiMbdAwVu7r4CA

###

### Eliminar un Evento 
DELETE http://localhost:5002/api/events/66e2e36feb449daaefd6e2d8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI2NTU2NjE5LCJleHAiOjE3MjcxNjE0MTl9.1ib6_QlnGDE2SE0jDdjDjpEz20DsTIvpACzS9DniEZk

###

### Test de MyEvents (obtener eventos futuros y pasados del usuario autenticado)
GET http://localhost:5002/api/events/user/myevents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZDU2NmJjYzA4MTkxZWVlMGFjMWU0ZiIsInVzZXJuYW1lIjoiY2VzYXJhbHZhcmV6bWFyaW5AZ21haWwuY29tIiwiaWF0IjoxNzI2NTEyOTIxLCJleHAiOjE3MjcxMTc3MjF9.Zo5DdzG9ehaw3Zzh4T3B25lszEiJKecgRDLh0-hJoqE
Content-Type: application/json


